//Each new term in the Fibonacci sequence is generated by adding the
//previous two terms. By starting with 1 and 2, the first 10 terms
//will be:  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do
// not exceed four million, find the sum of the even-valued terms.



// let a=0;
// let b=0;

// for(i=1;i<=4000000;i++){
//   if(i%2 ===0){
//     a = i;
//     b += i+a;
//   }
// }
// console.log(b);
//WRONG FORGOT TO ACCOUNT FOR FIB SEQUENCE


//sets up fibonacci sequence function
function* fibonacci(){
  //variables are 1 apart
  var dog = 0;
  var cat = 1;
  //while true loop will make current = dog
  while (true){
    var current = dog;
    dog = cat;
    cat = current + dog;
    var reset = yield current;
    if (reset){
        dog = 0;
        cat = 1;
    }
  }
}

//stores function in the variable called sequence
var sequence = fibonacci();

var sum = 0, i = sequence.next().value;
//while i is less than 4million, it will sum any numbers in the
//sequence that are even and then store that value in the var sum
while(i < 4000000){
    if(i % 2 === 0){
         sum += i;
    }
    i = sequence.next().value;
}

console.log(sum);
